image: node:10.15.3

clone:
  depth: full

pipelines:
  branches:
    develop:
      - step:
          name: Deploy to Heroku - Development
          caches:
            - node
          script:
            - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git